name: availability-test
on:
  workflow_dispatch:
  #schedule:
    #- cron: '0/5 * * * *'

defaults:
  run:
    working-directory: .

jobs:
  eshop_availability_test:
    runs-on: ubuntu-latest
    env:
      HOST: "eshop.6e04e4001e2942c89e57.eastus.aksapp.io"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: JMeter Availability Test
        uses: QAInsights/PerfAction@2.0
        with:
          test-plan-path: ./eshop-transaction-test.jmx
          args: "-Jurl=${{ env.HOST }}"
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
